services:
  app:
    image: ghcr.io/salvarez91/contacto-backend:latest
    container_name: contacto_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: contacto_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
